name: Make

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: initialize git config
      run: |
       git config --global user.email "test@example.com"
       git config --global user.name "Github Test User"
    - name: pull git submodules
      run: git submodule init && git submodule update
    - name: make
      run: make
